import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-section-179d-commercial-building-tax-deduction",
  "engine": "recovery",
  "title": "Section 179D Commercial Building Tax Deduction",
  "shortTitle": "Section 179D Commercial Building Tax Deduction",
  "tagline": "Quantify and document energy-efficiency deductions for qualifying commercial building systems and government-project allocations.",
  "industry": "Energy Tax Incentives",
  "buyer": "Commercial building owners and designers",
  "uiPort": 4681,
  "apiPort": 5681,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Section 179D Commercial Building Tax Deduction converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns in one accountable workflow. Quantify and document energy-efficiency deductions for qualifying commercial building systems and government-project allocations.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Section 179D Commercial Building Tax Deduction evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("building-project-registry","S1C01","Building project registry","Execute building project registry using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed building project registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Building project registry Reference","text","S1C01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("ownership-eligibility","S1C02","Ownership eligibility","Execute ownership eligibility using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed ownership eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Ownership eligibility Reference","text","S1C02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("government-allocation-control","S1C03","Government allocation control","Execute government allocation control using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed government allocation control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Government allocation control Reference","text","S1C03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("construction-cost-ingestion","S1C04","Construction cost ingestion","Execute construction cost ingestion using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed construction cost ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Construction cost ingestion Reference","text","S1C04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("lighting-system-evidence","S1C05","Lighting system evidence","Execute lighting system evidence using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed lighting system evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Lighting system evidence Reference","text","S1C05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("hvac-system-evidence","S1C06","HVAC system evidence","Execute hvac system evidence using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed hvac system evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","HVAC system evidence Reference","text","S1C06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("envelope-system-evidence","S1C07","Envelope system evidence","Execute envelope system evidence using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed envelope system evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Envelope system evidence Reference","text","S1C07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("energy-model-validation","S1C08","Energy model validation","Execute energy model validation using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed energy model validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Energy model validation Reference","text","S1C08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("reference-standard-mapping","S1C09","Reference standard mapping","Execute reference standard mapping using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed reference standard mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Reference standard mapping Reference","text","S1C09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("efficiency-threshold-calculation","S1C10","Efficiency threshold calculation","Execute efficiency threshold calculation using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed efficiency threshold calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Efficiency threshold calculation Reference","text","S1C10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("placed-in-service-validation","S1C11","Placed-in-service validation","Execute placed-in-service validation using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed placed-in-service validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Placed-in-service validation Reference","text","S1C11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("deduction-calculation","S1C12","Deduction calculation","Execute deduction calculation using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed deduction calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Deduction calculation Reference","text","S1C12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("certification-evidence","S1C13","Certification evidence","Execute certification evidence using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed certification evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Certification evidence Reference","text","S1C13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("return-workpaper-generation","S1C14","Return workpaper generation","Execute return workpaper generation using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed return workpaper generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Return workpaper generation Reference","text","S1C14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]}),
feature("building-tax-analytics","S1C15","Building tax analytics","Execute building tax analytics using building ownership, construction costs, energy models, lighting, HVAC, envelope systems, placed-in-service dates, allocation letters, certifications, and returns.","Produce a governed building tax analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Taxpayer / Building Project","text","Taxpayer / Building Project · Standard Case"],["caseReference","Building tax analytics Reference","text","S1C15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1030000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1246300],["domainDriver","Qualifying System","select","Lighting",["Lighting","HVAC","Building envelope"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Building project registry case","Ownership eligibility case","Government allocation control case","Construction cost ingestion case","Lighting system evidence case"]})
]);
